### PR TITLE
Update pyarrow version to 5.0.0

### PR DESCRIPTION
**Pull request by ldacey**
Addresses #318

### CODE REVIEW

**Comment by xhochy** [comment]
Can you also add an entry to the `.github/workflows/ci.yml` that will test against pyarrow 4/5?

**Comment by ldacey** [comment]
I made an attempt based on what I could see has been done historically. It seemed like I needed to update the Earthfile as well, so I added a test per version

**Comment by ldacey** [comment]
Were the tests I added incorrect? The build failed.

**Comment by xhochy** [comment]
> Were the tests I added incorrect? The build failed.

Looks good, seems like a versionong issue with the MS SQL driver. I can look into that next week. Otherwise, you can also try to find to new library name.

**Comment by ldacey** [comment]
I did a fresh install of msodbcsql17 on my machine and saw that the driver is now 17.8.so.1 instead of 17.7.so.2

```
ls /opt/microsoft/msodbcsql17/lib64/
libmsodbcsql-17.8.so.1.1
```

I updated the earthly/odbc/odbcinst.ini file to reflect this, hopefully that will work

**Review by xhochy — APPROVED** [review]
Thanks

**Pull request merged**
