### PR TITLE
Arrow 0.8.0 version update

### PR DESCRIPTION
**Pull request by xhochy**
Code changes that need to be done with `pyarrow==0.8.0`.  At the moment this is just for review.

### CODE REVIEW

**Comment by xhochy** [comment]
Note that 0.8.0 is not released yet.

**Comment by wesm** [comment]
Sorry about the breaking changes. Making `arrow::Table` abstract will help a lot longer term

**Comment by xhochy** [comment]
@MathMagique This is now ready to be merged. Looking forward for a new Arrow 0.8 compatible release.

**Comment by MathMagique** [comment]
Back from vacationing :-). Will have a look today or tomorrow!

**Comment by MathMagique** [comment]
Thanks for the update! Sorry for the long time it took to hit the merge button :-(

**Pull request merged**
